# Generated by Django 5.1.7 on 2025-03-13 06:03

from django.db import migrations

def insert_holidays(apps,schema_editor):
    TimeSlot = apps.get_model('timeschedulingweb','TimeSlots')
    TimeSlot(start_time='2025-05-01T00:00:00',
              end_time='2025-05-01T23:59:59',
              description='Independence day').save()
    TimeSlot(start_time='2025-12-25T00:00:00',
              end_time='2025-12-25T23:59:59',
              description='Religion Fest').save()
class Migration(migrations.Migration):

    dependencies = [
        ('timeschedulingweb', '0001_initial'),
    ]
 
    operations = [
        migrations.RunPython(insert_holidays)
    ]
